jmcollin78/versatile_thermostat

custom_components/versatile_thermostat/base_thermostat.py
tests/test_switch_ac.py

Hello Collin, 
I need the capability to switch from HEAT to COOL mode, does it make sense for you?
I have an aermec unit which can generate both cooling and heating, it is managed by ZBMINI-L2 ZigBee, if the thermostat is configured in AC mode I would like support both.
unit test updated as well!

switch from HEAT to COOL mode

---

README-fr.md
README.md
custom_components/versatile_thermostat/base_thermostat.py
tests/test_power.py

Hello, 
Reference Issue  #146 
Mean Power shouldn't multiply device_power by number of heater registered.
Also add a small information on that in the documentation.

Mean power Update

---

custom_components/versatile_thermostat/base_thermostat.py
tests/test_switch_ac.py

on my end I have those 2 condition always true 
self._ac_mode ==> true
not self.is_over_climate ==> true
so the find_preset_temp was always selecting the eco_ac on cool and heat mode

fix #185 switching from HEAT to COOL or viceversa

---

custom_components/versatile_thermostat/thermostat_climate.py

This MR fixes and issue where `_last_regulation_change` is set to `now` even though the new temperature setting is never sent to the thermostats, because `abs(dtemp) < self._auto_regulation_dtemp`

Only modify _last_regulation_change if new regulation is sent to thermostats

---

custom_components/versatile_thermostat/base_thermostat.py
custom_components/versatile_thermostat/select.py
custom_components/versatile_thermostat/thermostat_climate.py
custom_components/versatile_thermostat/thermostat_switch.py
custom_components/versatile_thermostat/thermostat_valve.py

This PR adds more type hints to selected files, mainly the thermostats classes. It started with wanting to know the type of the `config_entry` and `entry_infos` variables in the code, as I wondered if it was an object that had the same `get(key[, default])` method signature as the standard `dict` class. I found that yes, it does. Then I thought, _“Why don’t I add the type hint then?”_ From there it snowballed a bit and became this PR, but I think I am stopping here (I am not planning further PRs related to typing).
I don’t see type hints as just “hints for the developer that are ignored by the Python interpreter”, I see them as enabling the use of type checking tools such as `pyright` that help to avoid and catch bugs. Running `pyright` in the dev container (installed with `pip install …

Add more type hints in the thermostat classes and selected files

---

custom_components/versatile_thermostat/base_thermostat.py

Since updating to a recent version of Versatile Thermostat (I think v5.2.1 or later), my Home Assistant logs are flooded with the following info log messages (printed every 30 seconds), _even when the “Use window detection” checkbox is **unticked** in the configuration:_
```
2024-01-19 14:41:36.655 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] ... - Window auto event is ignored because bypass is ON or window auto detection is disabled
2024-01-19 14:42:06.693 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] ... - Window auto event is ignored because bypass is ON or window auto detection is disabled
2024-01-19 14:42:36.613 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] ... - Window auto event is ignored …
```

Change log level of “Window auto event is ignored” log message

---

README-fr.md
README.md

While adding documentation for PR #345, I edited configuration image files on my local workstation for the README files and previewed them locally with relative URLs, but I noticed that the majority of existing image URLs are absolute.
Is there a reason to prefer absolute image URLs in the README files? Relative URLs have the advantage that it is easier to preview modifications locally before committing the files to Github.
As for the `?raw=true` query string at the end of the absolute URLs, I gather that it causes a HTTP 302 redirect:
```sh
$ curl -v https://github.com/jmcollin78/versatile_thermostat/blob/main/images/new-icon.png?raw=true >/dev/null
...
< HTTP/2 302
< location: https://github.com/jmcollin78/versatile_thermostat/raw/main/images/new-icon.png
```
```
$ curl -v …
```

README*.md: Replace absolute image URLs with relative URLs

---

custom_components/versatile_thermostat/base_thermostat.py
custom_components/versatile_thermostat/prop_algorithm.py
custom_components/versatile_thermostat/thermostat_switch.py
custom_components/versatile_thermostat/thermostat_valve.py
tests/test_tpi.py

My Home Assistant logs were full of the following warning messages (printed about every 30 seconds) even though Versatile Thermostat was turned off (`self._hvac_mode is HVACMode.OFF`):
```
2024-02-04 17:02:53.951 WARNING (MainThread) [custom_components.versatile_thermostat.prop_algorithm] Proportional algorithm: calculation is not possible cause target_temp or current_temp is null. Heating/cooling will be disabled
2024-02-04 17:03:23.946 WARNING (MainThread) [custom_components.versatile_thermostat.prop_algorithm] Proportional algorithm: calculation is not possible cause target_temp or current_temp is null. Heating/cooling will be disabled
2024-02-04 17:03:53.978 WARNING (MainThread) [custom_components.versatile_thermostat.prop_algorithm] Proportional algorithm: calculation is not possible …
```

Prevent “Heating will be disabled” warning loop while HVACMode is OFF

---

custom_components/versatile_thermostat/underlyings.py
tests/test_switch_keep_alive.py

This PR is motivated by discussion #379. It is *not* clear that it fixes any bug, because we have *not* identified a bug: We have not been able to reproduce the issue reported by the user. All my tests — both automated unit tests and manual end-to-end tests — behaved the same way before and after this PR.
Having said that, the added logic in this PR fends off against some theoretical speculation of what might happen in some corner cases. See other comments for more details.

Make the switch keep-alive callback conditional on the entity state

---

.devcontainer/Dockerfile
.devcontainer/configuration.yaml
.devcontainer/devcontainer.json
.vscode/settings.json
requirements_dev.txt

The main benefit of this PR is to avoid the following `ffmpeg` error when starting Home Assistant in the VSCode devcontainer:
```
2024-02-15 19:35:54.772 ERROR (MainThread) [haffmpeg.core] FFmpeg fails [Errno 2] No such file or directory: 'ffmpeg'
Traceback (most recent call last):
File "/home/vscode/.local/lib/python3.11/site-packages/haffmpeg/core.py", line 137, in open
self._proc = await self._loop.run_in_executor(None, proc_func)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/subprocess.py", line 1026, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File …
```

Improvements to the development environment

---

custom_components/versatile_thermostat/base_thermostat.py
custom_components/versatile_thermostat/keep_alive.py
custom_components/versatile_thermostat/thermostat_climate.py
custom_components/versatile_thermostat/thermostat_switch.py
custom_components/versatile_thermostat/thermostat_valve.py
custom_components/versatile_thermostat/underlyings.py

This PR improves debugging diagnostics for the switch keep-alive feature for issues such as #379.
That’s achieved through one of the three commits. The other two commits improve type hints.

Expose the keep_alive_sec attribute in HASS Developer Tools - States

---

custom_components/versatile_thermostat/number.py
custom_components/versatile_thermostat/sensor.py
custom_components/versatile_thermostat/underlyings.py
tests/test_central_boiler.py
tests/test_central_config.py
tests/test_movement.py

With this change, I'm no longer affected by #240. 
I tried to write a unit test for this behavior, which would fail on main and pass on my branch, but I'm unfamiliar with python testing libraries, or how home assistant uses them, and wasn't able to figure it out.

[Draft] Use user's preferred temperature unit instead of hardcoding celsius

---

custom_components/versatile_thermostat/thermostat_climate.py
tests/test_auto_regulation.py

Hi,
I use Versatile thermostat from several weeks and really appreciate it to regulate my climate devices that have a bad thermal regulation because of the position of the sensor. Thank you for your big work on this. 
I suggest a small adjustment : a behavior that prevents the system from forgetting the regulation when using the device's internal temperature as an offset.
Although the regulation itself remains unchanged, variations in the device's internal temperature necessitate adjustments to the target temperature to maintain effective regulation. This code modification specifically bypasses the forget mechanism for minor adjustments, while the forget mechanism based on duration is still maintained.
Here is an history of the underlying climate before : 
and after (with 2 minutes of …

Enhance temperature regulation when working with internal device temperature

---

custom_components/versatile_thermostat/thermostat_climate.py
custom_components/versatile_thermostat/underlyings.py
requirements_dev.txt

With this change, I no longer suffer from #240. 
I made 2 basic changes to the code, simplifying the changes I mentioned in #240. 
- Firstly, I changed the unit used by VTherm to match HA's preferred unit.
- Secondly, I changed the references to the underlying entity's temperatures to use HA's state references. This automatically includes HA's converted values, and should be robust against having mismatched temperature units. I propose that all references to the underlying entity use HA's state, rather than directly accessing the values from the entity.
Example:
Change: 
`max_val = self._underlying_climate.max_temp`
To:
`max_val = self._hass.states.get(self._entity_id).attributes.get("max_temp")`
This results in the correct converted value being grabbed if the underlying entity uses a …

Change VTherm temperature unit to HA's preferred unit.

---

custom_components/versatile_thermostat/keep_alive.py
custom_components/versatile_thermostat/underlyings.py
tests/test_switch_keep_alive.py

Recently I powered off a heating appliance for the summer months (it will be used again when the weather gets colder). The appliance has a MQTT switch controlled by Versatile Thermostat using a thermostat-over-switch configuration with a short keep-alive period of 15 seconds. As a result of powering it off, the Home Assistant logs got flooded with the following warning messages, logged every 15 seconds:
```
2024-06-23 02:23:05.810 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities switch.my_switch are missing or not currently available
2024-06-23 02:23:20.813 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities switch.my_switch are missing or not currently available
2024-06-23 02:23:35.816 WARNING (MainThread) [homeassistant.helpers.service] …
```

Reduce keep-alive warning logs when the controlled entity becomes unavailable

---

custom_components/versatile_thermostat/__init__.py
custom_components/versatile_thermostat/base_thermostat.py
custom_components/versatile_thermostat/thermostat_climate.py
custom_components/versatile_thermostat/thermostat_switch.py
custom_components/versatile_thermostat/thermostat_valve.py

This PR fixes the following log warning messages printed when Home Assistant version 2024.7.1 starts:
```
2024-07-06 10:19:21.491 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] 
EventType was used from versatile_thermostat, this is a deprecated alias which will be removed in HA Core 2025.5.
Use homeassistant.core.Event instead, please report it to the author of the 'versatile_thermostat' custom integration
```
```
2024-07-06 10:19:21.601 WARNING (MainThread) [homeassistant.helpers.frame] 
Detected that custom integration 'versatile_thermostat' accesses hass.helpers.service.
This is deprecated and will stop working in Home Assistant 2024.11, it should be updated
to import functions used from service directly at custom_components/versatile_thermostat/__init__.py,
line 118: …
```

Fix Home Assistant deprecation warnings (EventType, helpers.service)

---

custom_components/versatile_thermostat/thermostat_climate.py

FIX #518 TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

FIX #518 TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

---

custom_components/versatile_thermostat/thermostat_climate.py
tests/test_overclimate.py

My initial goal was to filter out stupid data from my Bosch BTH-RA thermostat. But this change makes also sense in the grand scheme of things, because it unifies the user experience. It doesn't matter whether you change the target temperature via the HA frontend or directly with an underlying, min and max are considered in both scenarios.
At the moment there are no unit tests, as I still have to figure out how to create one for this scenario, but I will try to do that in the next days.
This implements #576.

Filter out-of-range target temperature sent from underlying climate devices

---

custom_components/versatile_thermostat/thermostat_climate.py

At the moment if a change event from an underlying has an out-of-range temperature, then the whole event is ignored. However this can lead to inconsisent states as relevant changes from the underlying might be ignored, i.e. `hvac_action`.
In this case the underlying will be in state `off/idle`, while the vtherm will stay in state `off/heating`. This will resolve itself eventually when another type of event comes in, e.g. from a temperature sensor. But until then it is confusing and annoying.
With this change just the detected target temperature change is filtered out, the other fields of the new underlying state can still be processed.
I'll add or change an unit test to cover this case, but won't have time for it until tonight. So please don't merge yet :smiley:

Fix side effect of out-of-range temperature filtering

---

README.md
custom_components/versatile_thermostat/__init__.py
custom_components/versatile_thermostat/base_thermostat.py
custom_components/versatile_thermostat/const.py
custom_components/versatile_thermostat/prop_algorithm.py
custom_components/versatile_thermostat/thermostat_switch.py
custom_components/versatile_thermostat/thermostat_valve.py
custom_components/versatile_thermostat/vtherm_api.py
tests/test_tpi.py

Implemented the `max_on_percent` expert level config to clamp the max ON time to a certain percentage of the cycle length. As discussed here https://github.com/jmcollin78/versatile_thermostat/discussions/602. 
`max_on_percent` can be set in the `configuration.yaml` like this: 
```
versatile_thermostat:
max_on_percent: 0.8
```
I have also added tests, to check if the calculation is done correctly. 
To avoid confusions, I also exposed the following attributes to HA:
```
max_on_percent
calculated_on_percent
```
Together with the already existing `on_percent` (which no can be clamped), all the informations are available to properly debug something if needed.

Implementing max_on_percent setting

---

custom_components/versatile_thermostat/auto_start_stop_algorithm.py
custom_components/versatile_thermostat/thermostat_climate.py
tests/test_auto_start_stop.py

Issue #625 - auto-start/stop change sometimes too fast

Issue #625 - auto-start/stop change sometimes too fast

---

custom_components/versatile_thermostat/climate.py

Fix for https://github.com/jmcollin78/versatile_thermostat/issues/717
`'Failed to perform the action versatile_thermostat.set_auto_regulation_mode. value must be one of ['Light', 'Medium', 'None', 'Slow', 'Strong'] for dictionary value @ data['auto_regulation_mode']. Got None'`

fix for 'It's not possible to set regulation mode to Expert using Automations'

---

custom_components/versatile_thermostat/base_thermostat.py
custom_components/versatile_thermostat/sensor.py
custom_components/versatile_thermostat/thermostat_climate_valve.py
tests/commons.py
tests/test_central_boiler.py
tests/test_overclimate_valve.py

Issue #698 nb device active for boiler not updating

Issue #698 nb device active for boiler not updating

---

custom_components/versatile_thermostat/base_thermostat.py
custom_components/versatile_thermostat/thermostat_climate.py
custom_components/versatile_thermostat/underlyings.py
documentation/en/reference.md
documentation/fr/reference.md
tests/test_auto_start_stop.py
tests/test_last_seen.py
tests/test_overclimate.py
tests/test_window.py

Issue #690 - VTherm don't follow underlying change with lastSeen activated

Issue #690 - VTherm don't follow underlying change with lastSeen activated

---

custom_components/versatile_thermostat/underlyings.py
tests/test_overclimate_valve.py

Modified 'percent_open' calculation method :
- Before : If percent_open < min_opening_degree then it is set to min_opening_degree
- Now : Each % step is calculated (100 - min_opening_degree)/100 so 1% ~> min_opening_degree
Sample :
- Before :
min_opening_degree = 15, percent calculated = 1, percent_open = 15
min_opening_degree = 15, percent calculated = 5, percent_open = 15
- Now :
min_opening_degree = 15, percent calculated = 1, percent open = round(15.85)
min_opening_degree = 15, percent calculated = 5, percent open = round(19.25)

Change percent_open calculation method

---

custom_components/versatile_thermostat/base_thermostat.py
custom_components/versatile_thermostat/manifest.json
requirements_dev.txt

issue #790 - hvac-off-reason is not restored after restart

issue #790 - hvac-off-reason is not restored after restart

---

custom_components/versatile_thermostat/feature_auto_start_stop_manager.py

Fixes #828 - `hvac_off_reason` could stay at `auto_start_stop` when the VTherm is 'on' (hvac_mode=Heat)

`hvac_off_reason` could stay at `auto_start_stop` when the VTherm is 'on' (hvac_mode=Heat)

---

custom_components/versatile_thermostat/feature_window_manager.py

Hello,
Il semblerait que le window_bypass n'est pas checké par la fonction permettant de retourner l'état des fenêtres.
Par conséquent, lors d'un changement de température alors que la fenêtre est ouverte il n'est pas exécuter .
J'en ai profiter pour changer la description de la fonction qui était un copier-coller.
Bonne journée,

Windows Bypass not checked

---

custom_components/versatile_thermostat/feature_window_manager.py

Hello,
Troisième petite modification : ``self._window_state`` n'est pas un booléen donc n'était jamais bloquant, il faut le comparer à ``STATE_ON`` .
J'en ai profité pour agréger les deux checks uniquement en cas de fenêtres ouvertes.
Bonne soirée

Set Windows Bypass

---

custom_components/versatile_thermostat/base_thermostat.py
custom_components/versatile_thermostat/config_schema.py

`cycle_min: 0` causes 100% load as timer gets scheduled in a loop with 0 delay #929

---

custom_components/versatile_thermostat/base_entity.py
custom_components/versatile_thermostat/number.py
custom_components/versatile_thermostat/switch.py

This assumes that in general all non climate entities are either DIAGNOSTIC or in the case of numbers and switches CONFIG entities, as the category is set in the custom base classes.
I have applied the patch to my own installation, but some more testing might be required. I do not know if the current approach by setting this in the base class is the best, but as only the climate entities should be primary this would ensure all relevant entities are affected.
Closes #1080

Add entity_category for all entities except climate

---

custom_components/versatile_thermostat/sensor.py

This sensors are prone to update very frequently, as per https://developers.home-assistant.io/docs/core/entity/#registry-properties set them to disabled by default.

Disable last temperature date sensors by default
