jmcollin78/versatile_thermostat

- README-fr.md
- README.md
- custom_components/versatile_thermostat/climate.py
- custom_components/versatile_thermostat/config_flow.py
- custom_components/versatile_thermostat/const.py
- custom_components/versatile_thermostat/strings.json
- custom_components/versatile_thermostat/translations/en.json
- custom_components/versatile_thermostat/translations/fr.json
Hello, 
As discussed, I have add a user defined threshold for the security preset to be activated
I can put an "input" instead of fixed value not sure we can have both available ? 
Regards,
> Minimal security threeshold

- .github/workflows/pull.yml
- custom_components/versatile_thermostat/climate.py
- custom_components/versatile_thermostat/manifest.json
- custom_components/versatile_thermostat/requirements_dev.txt
- custom_components/versatile_thermostat/requirements_test.txt
- custom_components/versatile_thermostat/tests/test_bugs.py
- custom_components/versatile_thermostat/tests/test_multiple_switch.py
- hacs.json
Fix bug #121
Test with HA 2023.10.3
Add unitary tests
> Bug #121 loop in over climate

- custom_components/versatile_thermostat/base_thermostat.py
- custom_components/versatile_thermostat/thermostat_climate.py
- custom_components/versatile_thermostat/thermostat_switch.py
- custom_components/versatile_thermostat/thermostat_valve.py
Add _entity_component_unrecorded_attributes to exclude attributes from record
> Issue #137 - limit the size of historical data

- custom_components/versatile_thermostat/underlyings.py
> FIX bug #136

- custom_components/versatile_thermostat/translations/en.json
Minor fixes in english text strings.
No code changes, only minor documentation edits.
> Fix english language translation strings

- README-fr.md
- README.md
- custom_components/versatile_thermostat/base_thermostat.py
- custom_components/versatile_thermostat/config_schema.py
- custom_components/versatile_thermostat/strings.json
- custom_components/versatile_thermostat/thermostat_valve.py
- custom_components/versatile_thermostat/translations/en.json
- custom_components/versatile_thermostat/translations/fr.json
- custom_components/versatile_thermostat/underlyings.py
- tests/test_central_boiler.py
- tests/test_valve.py
Added 2 parameters for `over_valve` VTherm to avoid drowning the battery (exactly as for regulation of `over_climate`)
> Issue 338 limit regulation over valve to avoid drowning battery of the TRV

- custom_components/versatile_thermostat/strings.json
- custom_components/versatile_thermostat/translations/en.json
-Translated strings in en.json
-Copied entire contents of en.json into strings.json
> English translations

- custom_components/versatile_thermostat/base_thermostat.py
https://github.com/jmcollin78/versatile_thermostat/issues/470
issue with ac and mouvement detection
> issue with ac and mouvement detection

- custom_components/versatile_thermostat/thermostat_climate.py
- tests/test_bugs.py
FIX #465 and make this coherent with Windows detection
> FIX #465 and make this coherent with Windows open/close

- custom_components/versatile_thermostat/underlyings.py
#554 - Add fake hvac_mode if underlying doesn't have one
> #554 - Add fake hvac_mode if underlying doesn't have one

- custom_components/versatile_thermostat/base_thermostat.py
- tests/test_movement.py
FIX issue #556 - enhance motion detection feature
> FIX issue #556 - enhance motion detection feature

- custom_components/versatile_thermostat/thermostat_climate.py
Issue #467 - Always apply offset compensation
> Issue #467 - Always apply offset compensation

- custom_components/versatile_thermostat/icons.json
- custom_components/versatile_thermostat/strings.json
- custom_components/versatile_thermostat/translations/en.json
- custom_components/versatile_thermostat/translations/fr.json
- custom_components/versatile_thermostat/translations/it.json
Addded Frost Preset to translations
Added Icons for Shedding, Safety, Manual and Frost Presets
> Preset display tweaks

- .devcontainer/configuration.yaml
- custom_components/versatile_thermostat/thermostat_climate.py
- tests/test_overclimate.py
Issue #615 - VTherm switch to manual on its own
> Issue #615 - VTherm switch to manual on its own

- custom_components/versatile_thermostat/base_thermostat.py
- tests/test_central_mode.py
- tests/test_overclimate.py
Issue #619 - manual hvac_off should be prioritized over window and auto-start/stop hvac_off
> Issue #619 - manual hvac_off should be prioritized over window and auto-start/stop hvac_off

- custom_components/versatile_thermostat/manifest.json
- custom_components/versatile_thermostat/thermostat_climate.py
- tests/test_auto_regulation.py
- tests/test_overclimate_valve.py
Issue #696 - follow underlying doesn't work anymore
> Issue #696   follow underlying doesn't work anymore

- custom_components/versatile_thermostat/manifest.json
- hacs.json
- requirements_dev.txt
issue #702 - migrate to HA 2024.12
> issue #702 - migrate to HA 2024.12

- custom_components/versatile_thermostat/config_flow.py
- custom_components/versatile_thermostat/config_schema.py
- custom_components/versatile_thermostat/const.py
- custom_components/versatile_thermostat/strings.json
- custom_components/versatile_thermostat/thermostat_climate_valve.py
- custom_components/versatile_thermostat/translations/en.json
- custom_components/versatile_thermostat/translations/fr.json
- custom_components/versatile_thermostat/underlyings.py
- tests/test_config_flow.py
- tests/test_overclimate_valve.py
Feature #722 - Add a minimum opening degree for valve regulation
> Feature #722 - Add a minimum opening degree for valve regulation

- .devcontainer/devcontainer.json
- custom_components/versatile_thermostat/base_thermostat.py
- tests/test_window.py
issue #683 - incorrect temperature reversion on window close
> issue #683 - incorrect temperature reversion on window close

- custom_components/versatile_thermostat/config_flow.py
issue #713 - config_entry is deprecated
> issue #713 - config_entry is deprecated

- custom_components/versatile_thermostat/base_entity.py
- custom_components/versatile_thermostat/base_thermostat.py
Removes typos and linter warnings for lines too long. Line lenght is 88, as per black default.
> (chore) Lint base_* files

- custom_components/versatile_thermostat/feature_presence_manager.py
- custom_components/versatile_thermostat/manifest.json
issue #759 - Frost temperature setpoint doesn't update with presence
> issue #759 - Frost temperature setpoint doesn't update with presence

- custom_components/versatile_thermostat/strings.json
- custom_components/versatile_thermostat/translations/en.json
Issue #805 - improve valve regulation config texts
> Issue #805 - improve valve regulation config texts

- custom_components/versatile_thermostat/underlyings.py
- tests/test_overclimate.py
issue #807 - send temperature only if in the feature
> issue #807 - send temperature only if in the feature

- custom_components/versatile_thermostat/manifest.json
- custom_components/versatile_thermostat/thermostat_climate_valve.py
- custom_components/versatile_thermostat/underlyings.py
Issue #804 - cannot set preset when follow is activated
> Issue #804 - cannot set preset when follow is activated

- custom_components/versatile_thermostat/sensor.py
Issue #779 - error in ValveOpenPercent sensor at startup
> Issue #779 - error in ValveOpenPercent sensor at startup

- custom_components/versatile_thermostat/base_thermostat.py
- custom_components/versatile_thermostat/manifest.json
- custom_components/versatile_thermostat/underlyings.py
- documentation/en/feature-power.md
- documentation/fr/feature-power.md
- tests/test_bugs.py
- tests/test_power.py
Issue #820 - improve power shedding algorithm
> Issue #820 - improve power shedding algorithm

- custom_components/versatile_thermostat/base_thermostat.py
- custom_components/versatile_thermostat/central_feature_power_manager.py
- custom_components/versatile_thermostat/feature_power_manager.py
- tests/test_binary_sensors.py
- tests/test_central_power_manager.py
- tests/test_motion.py
- tests/test_multiple_switch.py
- tests/test_power.py
- tests/test_window.py
> [Feature Request] - Pwoer shedding should prevent all VTherm to start at the same time

- custom_components/versatile_thermostat/translations/fr.json
Proposing 2 fixes on typos on the French translation.
Thanks for the great work!!!
> Fixes on FR translation

- custom_components/versatile_thermostat/base_thermostat.py
> Issue #846 - swicth Eco preset after Window close event

- .devcontainer/configuration.yaml
- custom_components/versatile_thermostat/manifest.json
- custom_components/versatile_thermostat/underlyings.py
- tests/test_inverted_switch.py
- tests/test_virtual_switch.py
> Release 7.2.0- Heating is inverted on `over_switch` with inverted commands ?

- custom_components/versatile_thermostat/feature_window_manager.py
Suite a ma réflexion sur #897 
Une PR pour récupérer l'etat de window_bypass
> Save & Recover Window Bypass state

- custom_components/versatile_thermostat/feature_window_manager.py
Comme discuté sur #899 - Utilisation de ```update_window_state`` pour le changement de ``window_bypass``
> Window bypass - use correct preset when window_action is set to Frost or Eco

- custom_components/versatile_thermostat/base_thermostat.py
- tests/test_window.py
Fix #962 - Preset changed when window is open and window action = turn_off
> fix Preset changed when window is open and window action = turn_off #962

- custom_components/versatile_thermostat/base_thermostat.py
- custom_components/versatile_thermostat/number.py
- tests/test_temp_number.py
> Thermostat with non central presets, "absent" presets are missing: #971

- custom_components/versatile_thermostat/thermostat_switch.py
- tests/test_power.py
> Total energy wrong when using multiple entities with one thermostat #877

- custom_components/versatile_thermostat/underlyings.py
- tests/test_overclimate_valve.py
> TRZVB not fully closed when heating is off in valve control mode #927

- custom_components/versatile_thermostat/underlyings.py
- tests/test_overclimate_valve.py
- tests/test_valve.py
> When TRV is offline, Vtherm continue to heats silently #948

- custom_components/versatile_thermostat/underlyings.py
- tests/test_overclimate_valve.py
- tests/test_valve.py
Reverts jmcollin78/versatile_thermostat#976
> Revert "When TRV is offline, Vtherm continue to heats silently #948"

- custom_components/versatile_thermostat/thermostat_climate_valve.py
- tests/test_overclimate_valve.py
> fix Sonoff TRVZB activate itself automatically when preset is changed on VTH despite VTherm is off #1012

- CONTRIBUTING-de.md
- README-de.md
- custom_components/versatile_thermostat/translations/de.json
Some typos have been corrected and the German translation has been completed.
> Correction typo, translation added

- custom_components/versatile_thermostat/base_thermostat.py
> Issue with respecting minimal_activation_delay_sec and minimal_deactivation_delay_sec

- custom_components/versatile_thermostat/config_schema.py
#1094 - allow negative threshold for TPI
> #1094 - allow negative threshold for TPI
